name: iot_tandon
description: Project Kuliah

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  firebase_core: ^1.20.0

  firebase_auth: ^3.5.0

  cloud_firestore: ^3.4.0

  firebase_database: ^9.0.20

  http: ^0.13.4

  modal_progress_hud_nsn: ^0.2.1

  rflutter_alert: ^2.0.4

  geolocator: ^9.0.1

  shared_preferences: ^2.0.15

  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/